//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_31_10
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymentDBEntities : DbContext
    {

        private static PaymentDBEntities _context;

        public static PaymentDBEntities GetContext()
        {
            if (_context == null)
                _context = new PaymentDBEntities();
            return _context;
        }

        public PaymentDBEntities()
            : base("name=PaymentDBEntities")
        {
        }

        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<payments> payments { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
